using System;
using System.Globalization;
using System.Net;
using System.Runtime.Versioning;

class Home
{

    bool creating = true;
    List<bool>roomAppliance = new List<bool>
    List<roomAppliance>rooms = new List<roomAppliance>

    public void roomCreate()
    {
        while(Home.creating == true)
        {
            

            Console.WriteLine("please write the name of the room");
            List<> roomName = Console.ReadLine();
            rooms.Append(List<>roomName);

            
            }

        }
        
    public void addAppliance()
    {
        bool addingAppliance = true;
        while(Home.addingAppliance == true)
            {
                Console.WriteLine("please put in smart appliance name in the room");
                bool appliance = Convert.ToBoolean(Console.ReadLine());
                room.Append(appliance)
                Console.WriteLine("Are there more appliances in this room Y/N:");
                string response = Console.ReadLine
                if(response == "n" or response == "N")
                {
                    addingAppliance = false;
                }
            }
    }
}




